// ============================================================
//  PREMIER LEAGUE BLACKJACK — DATA FILE
//  This is the ONLY file you need to edit to update the comp.
// ============================================================
//
//  TO UPDATE GOALS:  find the player in the PLAYERS list below
//                    and change their "goals" number.
//
//  TO MARK AS PAID:  in the ENTRIES list, change paid: false
//                    to paid: true for that person.
//
//  IF A PLAYER IS OUT FOR THE SEASON (injury, transfer abroad,
//  etc.):  add  out: true  to that player's line, e.g.
//                    { name: "Player", club: "ARS", goals: 0, out: true },
//                    Anyone holding an out player who scored ZERO
//                    goals busts. If they scored first, goals stay.
//
//  FORMAT:  4 players per entry · combined goals cap = 21 ·
//           go over 21 = BUST · all four must score at least
//           once by season end or the entry is void.
//
//  After editing, save/commit the file — the leaderboard
//  updates automatically.
// ============================================================

const CAP = 21;
const LAST_UPDATED = "3 September 2026 at 11:19";

// Club colours — primary hex used for the badge + accent bar.
// Add or edit clubs here; the 3-letter code is what players reference.
const CLUBS = {
  ARS: { name: "Arsenal",            color: "#EF0107" },
  AVL: { name: "Aston Villa",        color: "#95BFE5" },
  BOU: { name: "Bournemouth",        color: "#DA291C" },
  BRE: { name: "Brentford",          color: "#E30613" },
  BHA: { name: "Brighton",           color: "#0057B8" },
  CHE: { name: "Chelsea",            color: "#034694" },
  CRY: { name: "Crystal Palace",     color: "#1B458F" },
  EVE: { name: "Everton",            color: "#003399" },
  FUL: { name: "Fulham",             color: "#CFcfcf" },
  LEE: { name: "Leeds United",       color: "#FFE100" },
  LIV: { name: "Liverpool",          color: "#C8102E" },
  MCI: { name: "Man City",           color: "#6CABDD" },
  MUN: { name: "Man United",         color: "#DA291C" },
  NEW: { name: "Newcastle",          color: "#241F20" },
  NFO: { name: "Nottm Forest",       color: "#DD0000" },
  SUN: { name: "Sunderland",         color: "#EB172B" },
  TOT: { name: "Tottenham",          color: "#132257" },
  COV: { name: "Coventry City",      color: "#87CEEB" },
  HUL: { name: "Hull City",          color: "#F5A12D" },
  IPS: { name: "Ipswich Town",       color: "#3A64A3" },
};

// PLAYERS — edit goals here. "club" is the 3-letter code from CLUBS above.
const PLAYERS = [
  { name: "Brendan Aaronson",      club: "LEE", goals: 0, out: false },
  { name: "Alexis Mac Allister",   club: "LIV", goals: 0, out: false },
  { name: "Ethan Ampadu",          club: "LEE", goals: 0, out: false },
  { name: "Elliott Anderson",      club: "MCI", goals: 0, out: false },
  { name: "Taiwo Awoniyi",         club: "COV", goals: 0, out: false },
  { name: "Kevin Schade",          club: "BRE", goals: 1, out: false },
  { name: "Yasin Ayari",           club: "BHA", goals: 0, out: false },
  { name: "Harvey Barnes",         club: "NEW", goals: 0, out: false },
  { name: "Thierno Barry",         club: "EVE", goals: 1, out: false },
  { name: "Jaka Bijol",            club: "LEE", goals: 0, out: false },
  { name: "Enzo Fernandez",        club: "MCI", goals: 0, out: false },
  { name: "Jayden Bogle",          club: "LEE", goals: 0, out: false },
  { name: "Brian Brobbey",         club: "SUN", goals: 0, out: false },
  { name: "Emi Buendia",           club: "AVL", goals: 0, out: false },
  { name: "Dan Burn",              club: "NEW", goals: 0, out: false },
  { name: "Moises Caicedo",        club: "CHE", goals: 0, out: false },
  { name: "Ricardo Calafiori",     club: "ARS", goals: 0, out: false },
  { name: "Dominic Calvert-Lewin", club: "LEE", goals: 1, out: false },
  { name: "Rayan Cherki",          club: "MCI", goals: 2, out: false },
  { name: "Matheus Cunha",         club: "MUN", goals: 0, out: false },
  { name: "Mikel Damsgaard",       club: "BRE", goals: 0, out: false },
  { name: "Kiernan Dewsbury-Hall", club: "EVE", goals: 1, out: false },
  { name: "Amad Diallo",           club: "MUN", goals: 0, out: false },
  { name: "Virgil Van Dijk",       club: "LIV", goals: 0, out: false },
  { name: "Jeremy Doku",           club: "MCI", goals: 0, out: false },
  { name: "Patrick Dorgu",         club: "MUN", goals: 0, out: false },
  { name: "Lewis Dunk",            club: "BHA", goals: 0, out: false },
  { name: "Anthony Elanga",        club: "NEW", goals: 2, out: false },
  { name: "Enzo Le Fee",           club: "SUN", goals: 0, out: false },
  { name: "Bruno Fernandes",       club: "MUN", goals: 3, out: false },
  { name: "Mateus Fernandes",      club: "TOT", goals: 0, out: false },
  { name: "Phil Foden",            club: "MCI", goals: 0, out: false },
  { name: "Gabriel",               club: "ARS", goals: 0, out: false },
  { name: "Cody Gakpo",            club: "LIV", goals: 1, out: false },
  { name: "Alejandro Garnacho",    club: "AVL", goals: 0, out: false },
  { name: "Joe Gelhardt",          club: "HUL", goals: 0, out: false },
  { name: "Diego Gomez",           club: "BHA", goals: 0, out: false },
  { name: "Ryan Gravenberch",      club: "LIV", goals: 0, out: false },
  { name: "Archie Gray",           club: "TOT", goals: 0, out: false },
  { name: "Marc Guehi",            club: "MCI", goals: 1, out: false },
  { name: "Bruno Guimaraes",       club: "ARS", goals: 0, out: false },
  { name: "Josko Gvardiol",        club: "MCI", goals: 1, out: false },
  { name: "Kai Havertz",           club: "ARS", goals: 1, out: false },
  { name: "Jack Hinshelwood",      club: "BHA", goals: 2, out: false },
  { name: "Alexander Isak",        club: "LIV", goals: 1, out: false },
  { name: "Wilson Isidor",         club: "SUN", goals: 1, out: false },
  { name: "Alex Iwobi",            club: "FUL", goals: 0, out: false },
  { name: "Brennan Johnson",       club: "EVE", goals: 0, out: false },
  { name: "Justin Kluivert",       club: "BOU", goals: 0, out: false },
  { name: "Eli Junior Kroupi",     club: "BOU", goals: 0, out: false },
  { name: "Jorgen Strand Larsen",  club: "CRY", goals: 0, out: false },
  { name: "James Maddison",        club: "TOT", goals: 0, out: false },
  { name: "Harry Maguire",         club: "MUN", goals: 0, out: false },
  { name: "Kobbie Mainoo",         club: "MUN", goals: 0, out: false },
  { name: "Johan Manzambi",        club: "AVL", goals: 0, out: false },
  { name: "Ollie McBurnie",        club: "HUL", goals: 0, out: false },
  { name: "John McGinn",           club: "AVL", goals: 0, out: false },
  { name: "Mikel Merino",          club: "ARS", goals: 0, out: false },
  { name: "Kaoru Mitoma",          club: "BHA", goals: 0, out: false },
  { name: "Tarik Muharemovic",     club: "LEE", goals: 0, out: false },
  { name: "Daniel Munoz",          club: "NFO", goals: 1, out: false },
  { name: "Iliman Ndiaye",         club: "MCI", goals: 0, out: false },
  { name: "Pedro Neto",            club: "CHE", goals: 1, out: false },
  { name: "Lukas Nmecha",          club: "LEE", goals: 0, out: false },
  { name: "Nico O'Reilly",         club: "MCI", goals: 0, out: false },
  { name: "Martin Odegaard",       club: "ARS", goals: 1, out: false },
  { name: "Callum Hudson Odoi",    club: "NFO", goals: 0, out: false },
  { name: "Noah Okafor",           club: "LEE", goals: 0, out: false },
  { name: "William Osula",         club: "NEW", goals: 0, out: false },
  { name: "Dango Ouattara",        club: "BRE", goals: 0, out: false },
  { name: "Martin Palestra",       club: "CHE", goals: 0, out: false },
  { name: "Joao Pedro",            club: "CHE", goals: 2, out: false },
  { name: "Pedro Porro",           club: "TOT", goals: 0, out: false },
  { name: "Rayan",                 club: "BOU", goals: 0, out: false },
  { name: "Declan Rice",           club: "ARS", goals: 0, out: false },
  { name: "Morgan Rogers",         club: "CHE", goals: 1, out: false },
  { name: "Georginio Rutter",      club: "BHA", goals: 0, out: false },
  { name: "Bukayo Saka",           club: "ARS", goals: 2, out: false },
  { name: "Ismaila Sarr",          club: "CRY", goals: 0, out: false },
  { name: "Antoine Semenyo",       club: "MCI", goals: 0, out: false },
  { name: "Benjamin Sesko",        club: "MUN", goals: 0, out: false },
  { name: "Dominic Solanke",       club: "TOT", goals: 0, out: false },
  { name: "Anton Stach",           club: "LEE", goals: 1, out: false },
  { name: "Dominik Szoboszlai",    club: "LIV", goals: 1, out: false },
  { name: "James Tarkowski",       club: "EVE", goals: 1, out: false },
  { name: "Marcus Tavernier",      club: "BOU", goals: 1, out: false },
  { name: "Youri Tielemans",       club: "MUN", goals: 0, out: false },
  { name: "Sandro Tonali",         club: "TOT", goals: 0, out: false },
  { name: "Christos Tzolis",       club: "ARS", goals: 0, out: false },
  { name: "Micky Van de Ven",      club: "TOT", goals: 0, out: false },
  { name: "Luka Vuskovic",         club: "TOT", goals: 0, out: false },
  { name: "Morgan Gibbs White",    club: "NFO", goals: 1, out: false },
  { name: "Callum Wilson",         club: "BRE", goals: 0, out: false },
  { name: "Harry Wilson",          club: "LEE", goals: 0, out: false },
  { name: "Florian Wirtz",         club: "LIV", goals: 0, out: false },
  { name: "Martin Zubimendi",      club: "ARS", goals: 0, out: false },
];

// ENTRIES — each person picks 4 players (reference by exact name).
const ENTRIES = [
  { name: "Dave Jaques", paid: false, players: ["Bukayo Saka", "Virgil Van Dijk", "Harry Wilson", "Bruno Guimaraes"] },
  { name: "Chris Alloway", paid: true, players: ["Johan Manzambi", "Harry Wilson", "Mateus Fernandes", "Christos Tzolis"] },
  { name: "Ky Connolly", paid: true, players: ["Noah Okafor", "Gabriel", "James Maddison", "Bukayo Saka"] },
  { name: "Danny Bacon", paid: true, players: ["Jack Hinshelwood", "Virgil Van Dijk", "John McGinn", "Declan Rice"] },
  { name: "Greg Shales", paid: true, players: ["Noah Okafor", "Gabriel", "Nico O'Reilly", "John McGinn"] },
  { name: "James Waddy", paid: false, players: ["Youri Tielemans", "Nico O'Reilly", "Sandro Tonali", "Eli Junior Kroupi"] },
  { name: "John Wood", paid: true, players: ["Bruno Fernandes", "Diego Gomez", "Gabriel", "Mikel Damsgaard"] },
  { name: "Luke Waddington 2", paid: true, players: ["Georginio Rutter", "Jack Hinshelwood", "Diego Gomez", "Yasin Ayari"] },
  { name: "Connor Hickey", paid: true, players: ["Florian Wirtz", "Bruno Fernandes", "Luka Vuskovic", "Martin Palestra"] },
  { name: "Luke Jones", paid: true, players: ["Iliman Ndiaye", "Brennan Johnson", "Marcus Tavernier", "Jorgen Strand Larsen"] },
  { name: "Mitch Pearson", paid: true, players: ["Dan Burn", "Mikel Damsgaard", "Lewis Dunk", "Morgan Gibbs White"] },
  { name: "Lucy Harper", paid: true, players: ["Dominik Szoboszlai", "Nico O'Reilly", "Joe Gelhardt", "Brendan Aaronson"] },
  { name: "Kyle McKay 2", paid: true, players: ["Dominic Calvert-Lewin", "Harry Wilson", "Tarik Muharemovic", "Jayden Bogle"] },
  { name: "Gibbo", paid: true, players: ["Thierno Barry", "Gabriel", "Justin Kluivert", "Harry Wilson"] },
  { name: "Ben Hammond", paid: true, players: ["Harry Wilson", "Lukas Nmecha", "Noah Okafor", "Anton Stach"] },
  { name: "Nick Rego", paid: true, players: ["Harvey Barnes", "Gabriel", "Micky Van de Ven", "Dominik Szoboszlai"] },
  { name: "Lewis Hughes", paid: true, players: ["Harry Wilson", "Brennan Johnson", "Dominik Szoboszlai", "Virgil Van Dijk"] },
  { name: "Rob Dawson 2", paid: true, players: ["Anton Stach", "Mateus Fernandes", "Moises Caicedo", "Florian Wirtz"] },
  { name: "Jordan Hartley", paid: true, players: ["Kiernan Dewsbury-Hall", "John McGinn", "Pedro Porro", "Virgil Van Dijk"] },
  { name: "Kane Cooke", paid: true, players: ["Jeremy Doku", "Harry Wilson", "Dango Ouattara", "Dominik Szoboszlai"] },
  { name: "Rob Dawson 1", paid: true, players: ["Ryan Gravenberch", "Bruno Fernandes", "Ricardo Calafiori", "Marc Guehi"] },
  { name: "Josh Freeman", paid: true, players: ["Bruno Fernandes", "Cody Gakpo", "Declan Rice", "Jeremy Doku"] },
  { name: "Ashley Shepherd", paid: true, players: ["Archie Gray", "Morgan Rogers", "Declan Rice", "Kobbie Mainoo"] },
  { name: "Chris Hyett", paid: true, players: ["Anton Stach", "Jeremy Doku", "Gabriel", "Harvey Barnes"] },
  { name: "Chris Pitchford", paid: true, players: ["Elliott Anderson", "Alex Iwobi", "Dominik Szoboszlai", "Pedro Porro"] },
  { name: "Kyle McKay 1", paid: true, players: ["Kevin Schade", "Morgan Rogers", "Eli Junior Kroupi", "Wilson Isidor"] },
  { name: "Luke Waddington 1", paid: true, players: ["Marcus Tavernier", "Gabriel", "Dominik Szoboszlai", "Bruno Guimaraes"] },
  { name: "Josh Lees", paid: false, players: ["Emi Buendia", "Harry Wilson", "Enzo Le Fee", "Jack Hinshelwood"] },
  { name: "Glynn Bateson", paid: true, players: ["Wilson Isidor", "Jack Hinshelwood", "Anton Stach", "Rayan Cherki"] },
  { name: "Liam McGuire", paid: true, players: ["Virgil Van Dijk", "Alejandro Garnacho", "Youri Tielemans", "Harry Wilson"] },
  { name: "Tom Dodd", paid: true, players: ["Iliman Ndiaye", "Daniel Munoz", "John McGinn", "Kevin Schade"] },
  { name: "Max Thomson", paid: true, players: ["Ollie McBurnie", "Declan Rice", "Gabriel", "Nico O'Reilly"] },
  { name: "Ryan Guant", paid: true, players: ["Rayan", "Anton Stach", "Ismaila Sarr", "Jaka Bijol"] },
  { name: "Dan Shaw", paid: true, players: ["Joao Pedro", "Harry Wilson", "Youri Tielemans", "Callum Wilson"] },
  { name: "Rich Ingman", paid: true, players: ["Declan Rice", "Marc Guehi", "Pedro Porro", "Harry Wilson"] },
  { name: "Rob Crampton 1", paid: true, players: ["Jeremy Doku", "Bukayo Saka", "Sandro Tonali", "Josko Gvardiol"] },
  { name: "Rob Crampton 2", paid: true, players: ["Matheus Cunha", "Martin Odegaard", "Virgil Van Dijk", "Nico O'Reilly"] },
  { name: "Liam Todd", paid: true, players: ["Virgil Van Dijk", "Declan Rice", "Dominik Szoboszlai", "Nico O'Reilly"] },
  { name: "Rachel Tarbuck", paid: true, players: ["Phil Foden", "Ollie McBurnie", "Dominic Solanke", "Dan Burn"] },
  { name: "Martin Carberry", paid: true, players: ["Florian Wirtz", "Nico O'Reilly", "John McGinn", "Martin Zubimendi"] },
  { name: "Danny Bradley", paid: true, players: ["Kai Havertz", "Anthony Elanga", "Daniel Munoz", "Ethan Ampadu"] },
  { name: "Sammie Bradley", paid: true, players: ["Jayden Bogle", "Harry Wilson", "Noah Okafor", "Anton Stach"] },
  { name: "Saq Hussain", paid: true, players: ["Virgil Van Dijk", "Declan Rice", "Nico O'Reilly", "Daniel Munoz"] },
  { name: "Jack Lovett", paid: true, players: ["Nico O'Reilly", "Declan Rice", "Enzo Le Fee", "Micky Van de Ven"] },
  { name: "Matty Capstick", paid: true, players: ["Benjamin Sesko", "Amad Diallo", "Patrick Dorgu", "Harry Maguire"] },
  { name: "Chris Beard", paid: true, players: ["Alexander Isak", "Declan Rice", "Antoine Semenyo", "Virgil Van Dijk"] },
  { name: "Andrew Siddle", paid: true, players: ["Dango Ouattara", "Anton Stach", "Dominik Szoboszlai", "John McGinn"] },
  { name: "George Bason", paid: true, players: ["Callum Hudson Odoi", "Brian Brobbey", "Taiwo Awoniyi", "Ollie McBurnie"] },
  { name: "Dan Cook", paid: true, players: ["Dominik Szoboszlai", "Mikel Merino", "Harry Wilson", "Daniel Munoz"] },
  { name: "Tom Pick", paid: true, players: ["Virgil Van Dijk", "Bruno Guimaraes", "Youri Tielemans", "Harry Maguire"] },
  { name: "Jacob Gallie", paid: true, players: ["Pedro Neto", "Declan Rice", "Dominik Szoboszlai", "Jack Hinshelwood"] },
  { name: "Louie Wilson", paid: true, players: ["James Tarkowski", "John McGinn", "Dominik Szoboszlai", "Nico O'Reilly"] },
  { name: "Kieren Barnes", paid: true, players: ["Jeremy Doku", "Cody Gakpo", "Declan Rice", "Antoine Semenyo"] },
  { name: "Lee Sykes", paid: true, players: ["Bukayo Saka", "Gabriel", "Micky Van de Ven", "Anton Stach"] },
  { name: "Chris Hatherly", paid: true, players: ["William Osula", "Harvey Barnes", "Micky Van de Ven", "Dominik Szoboszlai"] },
  { name: "Kyle Cleobury", paid: true, players: ["Declan Rice", "Virgil Van Dijk", "Kiernan Dewsbury-Hall", "Dominik Szoboszlai"] },
  { name: "Craig Allan", paid: true, players: ["Bruno Guimaraes", "Nico O'Reilly", "Kiernan Dewsbury-Hall", "Alexis Mac Allister"] },
  { name: "Paul Eyre", paid: true, players: ["Emi Buendia", "Harry Maguire", "Ismaila Sarr", "Tarik Muharemovic"] },
  { name: "Tom King", paid: true, players: ["Dominic Solanke", "Morgan Rogers", "Kaoru Mitoma", "Antoine Semenyo"] },
  { name: "Adam Fretwell", paid: false, players: ["Bruno Fernandes", "Enzo Fernandez", "Mateus Fernandes", "Ricardo Calafiori"] },
];
